# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frorm.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(690, 366)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 221, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 2, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 2, 1)
        self.n = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.n.setObjectName("n")
        self.gridLayout.addWidget(self.n, 4, 2, 1, 2)
        self.d11 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.d11.setObjectName("d11")
        self.gridLayout.addWidget(self.d11, 2, 1, 1, 1)
        self.p1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.p1.setObjectName("p1")
        self.gridLayout.addWidget(self.p1, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 2)
        self.d21 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.d21.setObjectName("d21")
        self.gridLayout.addWidget(self.d21, 2, 3, 1, 1)
        self.p2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.p2.setObjectName("p2")
        self.gridLayout.addWidget(self.p2, 3, 3, 1, 1)
        self.m21 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.m21.setObjectName("m21")
        self.gridLayout.addWidget(self.m21, 0, 3, 2, 1)
        self.m11 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.m11.setInputMethodHints(QtCore.Qt.ImhNone)
        self.m11.setPlaceholderText("")
        self.m11.setObjectName("m11")
        self.gridLayout.addWidget(self.m11, 0, 1, 2, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(520, 10, 104, 152))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graph_pmist_n_btn = QtWidgets.QPushButton(self.groupBox)
        self.graph_pmist_n_btn.setObjectName("graph_pmist_n_btn")
        self.verticalLayout.addWidget(self.graph_pmist_n_btn)
        self.graph_pmist_prior_btn = QtWidgets.QPushButton(self.groupBox)
        self.graph_pmist_prior_btn.setObjectName("graph_pmist_prior_btn")
        self.verticalLayout.addWidget(self.graph_pmist_prior_btn)
        self.graph_pmist_m_btn = QtWidgets.QPushButton(self.groupBox)
        self.graph_pmist_m_btn.setObjectName("graph_pmist_m_btn")
        self.verticalLayout.addWidget(self.graph_pmist_m_btn)
        self.graph_pmist_d_btn = QtWidgets.QPushButton(self.groupBox)
        self.graph_pmist_d_btn.setObjectName("graph_pmist_d_btn")
        self.verticalLayout.addWidget(self.graph_pmist_d_btn)
        self.isUseCLT = QtWidgets.QCheckBox(Form)
        self.isUseCLT.setEnabled(True)
        self.isUseCLT.setGeometry(QtCore.QRect(10, 200, 141, 21))
        self.isUseCLT.setObjectName("isUseCLT")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(250, 10, 251, 243))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.p2_ev = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.p2_ev.setText("")
        self.p2_ev.setObjectName("p2_ev")
        self.gridLayout_2.addWidget(self.p2_ev, 3, 3, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 5, 0, 1, 1)
        self.p_mist1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.p_mist1.setText("")
        self.p_mist1.setObjectName("p_mist1")
        self.gridLayout_2.addWidget(self.p_mist1, 5, 1, 1, 1)
        self.p_mist2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.p_mist2.setText("")
        self.p_mist2.setObjectName("p_mist2")
        self.gridLayout_2.addWidget(self.p_mist2, 5, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 4, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 3, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 0, 2, 2, 1)
        self.m11_ev = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.m11_ev.setText("")
        self.m11_ev.setObjectName("m11_ev")
        self.gridLayout_2.addWidget(self.m11_ev, 0, 1, 2, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 0, 2, 1)
        self.m21_ev = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.m21_ev.setText("")
        self.m21_ev.setObjectName("m21_ev")
        self.gridLayout_2.addWidget(self.m21_ev, 0, 3, 2, 1)
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_39.setObjectName("label_39")
        self.gridLayout_2.addWidget(self.label_39, 5, 2, 1, 1)
        self.d11_ev = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.d11_ev.setText("")
        self.d11_ev.setObjectName("d11_ev")
        self.gridLayout_2.addWidget(self.d11_ev, 2, 1, 1, 1)
        self.d21_ev = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.d21_ev.setText("")
        self.d21_ev.setObjectName("d21_ev")
        self.gridLayout_2.addWidget(self.d21_ev, 2, 3, 1, 1)
        self.p1_ev = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.p1_ev.setText("")
        self.p1_ev.setObjectName("p1_ev")
        self.gridLayout_2.addWidget(self.p1_ev, 3, 1, 1, 1)
        self.n2_res = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.n2_res.setText("")
        self.n2_res.setObjectName("n2_res")
        self.gridLayout_2.addWidget(self.n2_res, 4, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 4, 0, 1, 1)
        self.p_mist = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.p_mist.setText("")
        self.p_mist.setObjectName("p_mist")
        self.gridLayout_2.addWidget(self.p_mist, 6, 2, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 3, 2, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_41.setObjectName("label_41")
        self.gridLayout_2.addWidget(self.label_41, 6, 0, 1, 2)
        self.n1_res = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.n1_res.setText("")
        self.n1_res.setObjectName("n1_res")
        self.gridLayout_2.addWidget(self.n1_res, 4, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(10, 230, 21, 16))
        self.label_23.setObjectName("label_23")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(250, 270, 251, 61))
        self.pushButton.setObjectName("pushButton")
        self.k = QtWidgets.QLineEdit(Form)
        self.k.setEnabled(True)
        self.k.setGeometry(QtCore.QRect(40, 230, 41, 23))
        self.k.setObjectName("k")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(230, 0, 20, 271))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(500, 0, 20, 271))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 260, 101, 85))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.q = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.q.setObjectName("q")
        self.gridLayout_3.addWidget(self.q, 2, 1, 1, 1)
        self.c = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.c.setObjectName("c")
        self.gridLayout_3.addWidget(self.c, 1, 1, 1, 1)
        self.h = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.h.setText("")
        self.h.setObjectName("h")
        self.gridLayout_3.addWidget(self.h, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 290, 142, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.core_type = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.core_type.setObjectName("core_type")
        self.core_type.addItem("")
        self.core_type.addItem("")
        self.core_type.addItem("")
        self.core_type.addItem("")
        self.core_type.addItem("")
        self.verticalLayout_2.addWidget(self.core_type)
        self.is_h_opt = QtWidgets.QCheckBox(Form)
        self.is_h_opt.setGeometry(QtCore.QRect(100, 230, 97, 22))
        self.is_h_opt.setObjectName("is_h_opt")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "M11"))
        self.label_10.setText(_translate("Form", "P2"))
        self.label_6.setText(_translate("Form", "D21"))
        self.label_3.setText(_translate("Form", "D11"))
        self.label_4.setText(_translate("Form", "M21"))
        self.n.setText(_translate("Form", "100"))
        self.d11.setText(_translate("Form", "4"))
        self.p1.setText(_translate("Form", "0.5"))
        self.label_9.setText(_translate("Form", "P1"))
        self.label_11.setText(_translate("Form", "N"))
        self.d21.setText(_translate("Form", "5"))
        self.p2.setText(_translate("Form", "0.5"))
        self.m21.setText(_translate("Form", "15"))
        self.m11.setText(_translate("Form", "10"))
        self.groupBox.setTitle(_translate("Form", "Графики"))
        self.graph_pmist_n_btn.setText(_translate("Form", "Pош/N"))
        self.graph_pmist_prior_btn.setText(_translate("Form", "Pош/P"))
        self.graph_pmist_m_btn.setText(_translate("Form", "Pош/h"))
        self.graph_pmist_d_btn.setText(_translate("Form", "Pош/Ядро"))
        self.isUseCLT.setText(_translate("Form", "Генератор ЦПТ"))
        self.label_37.setText(_translate("Form", "Pmist1"))
        self.label_15.setText(_translate("Form", "D2"))
        self.label_35.setText(_translate("Form", "N2"))
        self.label_21.setText(_translate("Form", "P1"))
        self.label_13.setText(_translate("Form", "D1"))
        self.label_20.setText(_translate("Form", "M2"))
        self.label_16.setText(_translate("Form", "M1"))
        self.label_39.setText(_translate("Form", "Pmist2"))
        self.label_22.setText(_translate("Form", "N1"))
        self.label_12.setText(_translate("Form", "P2"))
        self.label_41.setText(_translate("Form", "Pmist"))
        self.label_23.setText(_translate("Form", "K"))
        self.pushButton.setText(_translate("Form", "Рассчитать"))
        self.k.setText(_translate("Form", "12"))
        self.label_5.setText(_translate("Form", "q"))
        self.label_7.setText(_translate("Form", "c"))
        self.q.setText(_translate("Form", "0.2"))
        self.c.setText(_translate("Form", "1"))
        self.label_14.setText(_translate("Form", "h"))
        self.label_8.setText(_translate("Form", "Тип ядра"))
        self.core_type.setItemText(0, _translate("Form", "Прямоугольное"))
        self.core_type.setItemText(1, _translate("Form", "Треугольное"))
        self.core_type.setItemText(2, _translate("Form", "Епанечникова"))
        self.core_type.setItemText(3, _translate("Form", "Гаусса"))
        self.core_type.setItemText(4, _translate("Form", "Квадратичное"))
        self.is_h_opt.setText(_translate("Form", "Подбор h"))
