# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mad1.ui'
#
# Created: Mon Jan 11 13:59:29 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(706, 288)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 221, 215))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 2, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 2, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 6, 2, 1, 2)
        self.m12 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.m12.setObjectName("m12")
        self.gridLayout.addWidget(self.m12, 2, 1, 1, 1)
        self.d11 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.d11.setObjectName("d11")
        self.gridLayout.addWidget(self.d11, 3, 1, 1, 1)
        self.d12 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.d12.setObjectName("d12")
        self.gridLayout.addWidget(self.d12, 4, 1, 1, 1)
        self.p1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.p1.setObjectName("p1")
        self.gridLayout.addWidget(self.p1, 5, 1, 1, 1)
        self.m22 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.m22.setObjectName("m22")
        self.gridLayout.addWidget(self.m22, 2, 3, 1, 1)
        self.d21 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.d21.setObjectName("d21")
        self.gridLayout.addWidget(self.d21, 3, 3, 1, 1)
        self.d22 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.d22.setObjectName("d22")
        self.gridLayout.addWidget(self.d22, 4, 3, 1, 1)
        self.p2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.p2.setObjectName("p2")
        self.gridLayout.addWidget(self.p2, 5, 3, 1, 1)
        self.m21 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.m21.setObjectName("m21")
        self.gridLayout.addWidget(self.m21, 0, 3, 2, 1)
        self.m11 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.m11.setInputMethodHints(QtCore.Qt.ImhNone)
        self.m11.setObjectName("m11")
        self.gridLayout.addWidget(self.m11, 0, 1, 2, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(250, 20, 251, 227))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.n1_res = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.n1_res.setText("")
        self.n1_res.setObjectName("n1_res")
        self.gridLayout_2.addWidget(self.n1_res, 6, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 7, 0, 1, 1)
        self.p_mist1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.p_mist1.setText("")
        self.p_mist1.setObjectName("p_mist1")
        self.gridLayout_2.addWidget(self.p_mist1, 7, 1, 1, 1)
        self.p_mist2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.p_mist2.setText("")
        self.p_mist2.setObjectName("p_mist2")
        self.gridLayout_2.addWidget(self.p_mist2, 7, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 3, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 4, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 4, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 6, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 5, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 0, 2, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 0, 2, 2, 1)
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_39.setObjectName("label_39")
        self.gridLayout_2.addWidget(self.label_39, 7, 2, 1, 1)
        self.m11_ev = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.m11_ev.setText("")
        self.m11_ev.setObjectName("m11_ev")
        self.gridLayout_2.addWidget(self.m11_ev, 0, 1, 2, 1)
        self.m21_ev = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.m21_ev.setText("")
        self.m21_ev.setObjectName("m21_ev")
        self.gridLayout_2.addWidget(self.m21_ev, 0, 3, 2, 1)
        self.m12_ev = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.m12_ev.setText("")
        self.m12_ev.setObjectName("m12_ev")
        self.gridLayout_2.addWidget(self.m12_ev, 2, 1, 1, 1)
        self.m22_ev = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.m22_ev.setText("")
        self.m22_ev.setObjectName("m22_ev")
        self.gridLayout_2.addWidget(self.m22_ev, 2, 3, 1, 1)
        self.d11_ev = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.d11_ev.setText("")
        self.d11_ev.setObjectName("d11_ev")
        self.gridLayout_2.addWidget(self.d11_ev, 3, 1, 1, 1)
        self.d21_ev = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.d21_ev.setText("")
        self.d21_ev.setObjectName("d21_ev")
        self.gridLayout_2.addWidget(self.d21_ev, 3, 3, 1, 1)
        self.d12_ev = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.d12_ev.setText("")
        self.d12_ev.setObjectName("d12_ev")
        self.gridLayout_2.addWidget(self.d12_ev, 4, 1, 1, 1)
        self.d22_ev = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.d22_ev.setText("")
        self.d22_ev.setObjectName("d22_ev")
        self.gridLayout_2.addWidget(self.d22_ev, 4, 3, 1, 1)
        self.p1_ev = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.p1_ev.setText("")
        self.p1_ev.setObjectName("p1_ev")
        self.gridLayout_2.addWidget(self.p1_ev, 5, 1, 1, 1)
        self.n2_res = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.n2_res.setText("")
        self.n2_res.setObjectName("n2_res")
        self.gridLayout_2.addWidget(self.n2_res, 6, 3, 1, 1)
        self.p2_ev = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.p2_ev.setText("")
        self.p2_ev.setObjectName("p2_ev")
        self.gridLayout_2.addWidget(self.p2_ev, 5, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 6, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_41.setObjectName("label_41")
        self.gridLayout_2.addWidget(self.label_41, 8, 0, 1, 2)
        self.p_mist = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.p_mist.setObjectName("p_mist")
        self.gridLayout_2.addWidget(self.p_mist, 8, 2, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 5, 2, 1, 1)
        self.isUseCLT = QtWidgets.QCheckBox(self.centralwidget)
        self.isUseCLT.setGeometry(QtCore.QRect(10, 240, 121, 21))
        self.isUseCLT.setObjectName("isUseCLT")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(140, 260, 80, 23))
        self.pushButton.setObjectName("pushButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(230, 10, 20, 271))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.k = QtWidgets.QLineEdit(self.centralwidget)
        self.k.setGeometry(QtCore.QRect(40, 260, 41, 23))
        self.k.setObjectName("k")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(10, 260, 21, 16))
        self.label_23.setObjectName("label_23")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(500, 10, 20, 271))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(520, 20, 104, 152))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graph_pmist_n_btn = QtWidgets.QPushButton(self.groupBox)
        self.graph_pmist_n_btn.setObjectName("graph_pmist_n_btn")
        self.verticalLayout.addWidget(self.graph_pmist_n_btn)
        self.graph_pmist_prior_btn = QtWidgets.QPushButton(self.groupBox)
        self.graph_pmist_prior_btn.setObjectName("graph_pmist_prior_btn")
        self.verticalLayout.addWidget(self.graph_pmist_prior_btn)
        self.graph_pmist_m_btn = QtWidgets.QPushButton(self.groupBox)
        self.graph_pmist_m_btn.setObjectName("graph_pmist_m_btn")
        self.verticalLayout.addWidget(self.graph_pmist_m_btn)
        self.graph_pmist_d_btn = QtWidgets.QPushButton(self.groupBox)
        self.graph_pmist_d_btn.setObjectName("graph_pmist_d_btn")
        self.verticalLayout.addWidget(self.graph_pmist_d_btn)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_10.setText(_translate("MainWindow", "P2"))
        self.label_3.setText(_translate("MainWindow", "D11"))
        self.label_5.setText(_translate("MainWindow", "M22"))
        self.label_6.setText(_translate("MainWindow", "D21"))
        self.label.setText(_translate("MainWindow", "M11"))
        self.label_7.setText(_translate("MainWindow", "D12"))
        self.label_8.setText(_translate("MainWindow", "D22"))
        self.label_2.setText(_translate("MainWindow", "M12"))
        self.label_4.setText(_translate("MainWindow", "M21"))
        self.label_9.setText(_translate("MainWindow", "P1"))
        self.label_11.setText(_translate("MainWindow", "N"))
        self.label_37.setText(_translate("MainWindow", "Pmist1"))
        self.label_15.setText(_translate("MainWindow", "D21"))
        self.label_18.setText(_translate("MainWindow", "D22"))
        self.label_17.setText(_translate("MainWindow", "D12"))
        self.label_35.setText(_translate("MainWindow", "N2"))
        self.label_21.setText(_translate("MainWindow", "P1"))
        self.label_19.setText(_translate("MainWindow", "M12"))
        self.label_13.setText(_translate("MainWindow", "D11"))
        self.label_14.setText(_translate("MainWindow", "M22"))
        self.label_16.setText(_translate("MainWindow", "M11"))
        self.label_20.setText(_translate("MainWindow", "M21"))
        self.label_39.setText(_translate("MainWindow", "Pmist2"))
        self.label_22.setText(_translate("MainWindow", "N1"))
        self.label_41.setText(_translate("MainWindow", "Pmist"))
        self.p_mist.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "P2"))
        self.isUseCLT.setText(_translate("MainWindow", "Генератор ЦПТ"))
        self.pushButton.setText(_translate("MainWindow", "Рассчитать"))
        self.label_23.setText(_translate("MainWindow", "K"))
        self.groupBox.setTitle(_translate("MainWindow", "Графики"))
        self.graph_pmist_n_btn.setText(_translate("MainWindow", "Pош/N"))
        self.graph_pmist_prior_btn.setText(_translate("MainWindow", "Pош/P"))
        self.graph_pmist_m_btn.setText(_translate("MainWindow", "Pош/M"))
        self.graph_pmist_d_btn.setText(_translate("MainWindow", "Pош/D"))

